# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


import pyfjcore



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _eec
else:
    import _eec

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _eec.SWIG_PyInstanceMethod_New
_swig_new_static_method = _eec.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    r"""Proxy of C++ swig::SwigPyIterator class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _eec.delete_SwigPyIterator
    value = _swig_new_instance_method(_eec.SwigPyIterator_value)
    incr = _swig_new_instance_method(_eec.SwigPyIterator_incr)
    decr = _swig_new_instance_method(_eec.SwigPyIterator_decr)
    distance = _swig_new_instance_method(_eec.SwigPyIterator_distance)
    equal = _swig_new_instance_method(_eec.SwigPyIterator_equal)
    copy = _swig_new_instance_method(_eec.SwigPyIterator_copy)
    next = _swig_new_instance_method(_eec.SwigPyIterator_next)
    __next__ = _swig_new_instance_method(_eec.SwigPyIterator___next__)
    previous = _swig_new_instance_method(_eec.SwigPyIterator_previous)
    advance = _swig_new_instance_method(_eec.SwigPyIterator_advance)
    __eq__ = _swig_new_instance_method(_eec.SwigPyIterator___eq__)
    __ne__ = _swig_new_instance_method(_eec.SwigPyIterator___ne__)
    __iadd__ = _swig_new_instance_method(_eec.SwigPyIterator___iadd__)
    __isub__ = _swig_new_instance_method(_eec.SwigPyIterator___isub__)
    __add__ = _swig_new_instance_method(_eec.SwigPyIterator___add__)
    __sub__ = _swig_new_instance_method(_eec.SwigPyIterator___sub__)
    def __iter__(self):
        return self

# Register SwigPyIterator in _eec:
_eec.SwigPyIterator_swigregister(SwigPyIterator)

import pyfjcore

from pyfjcore import FastJetError


import numpy as _np

class arrayDouble2(object):
    r"""Proxy of C++ std::array< double,2 > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iterator = _swig_new_instance_method(_eec.arrayDouble2_iterator)
    def __iter__(self):
        return self.iterator()
    __nonzero__ = _swig_new_instance_method(_eec.arrayDouble2___nonzero__)
    __bool__ = _swig_new_instance_method(_eec.arrayDouble2___bool__)
    __len__ = _swig_new_instance_method(_eec.arrayDouble2___len__)
    __getslice__ = _swig_new_instance_method(_eec.arrayDouble2___getslice__)
    __setslice__ = _swig_new_instance_method(_eec.arrayDouble2___setslice__)
    __delslice__ = _swig_new_instance_method(_eec.arrayDouble2___delslice__)
    __delitem__ = _swig_new_instance_method(_eec.arrayDouble2___delitem__)
    __getitem__ = _swig_new_instance_method(_eec.arrayDouble2___getitem__)
    __setitem__ = _swig_new_instance_method(_eec.arrayDouble2___setitem__)

    def __init__(self, *args):
        r"""
        __init__(arrayDouble2 self) -> arrayDouble2
        __init__(arrayDouble2 self, arrayDouble2 other) -> arrayDouble2
        """
        _eec.arrayDouble2_swiginit(self, _eec.new_arrayDouble2(*args))
    empty = _swig_new_instance_method(_eec.arrayDouble2_empty)
    size = _swig_new_instance_method(_eec.arrayDouble2_size)
    swap = _swig_new_instance_method(_eec.arrayDouble2_swap)
    begin = _swig_new_instance_method(_eec.arrayDouble2_begin)
    end = _swig_new_instance_method(_eec.arrayDouble2_end)
    rbegin = _swig_new_instance_method(_eec.arrayDouble2_rbegin)
    rend = _swig_new_instance_method(_eec.arrayDouble2_rend)
    front = _swig_new_instance_method(_eec.arrayDouble2_front)
    back = _swig_new_instance_method(_eec.arrayDouble2_back)
    fill = _swig_new_instance_method(_eec.arrayDouble2_fill)
    __swig_destroy__ = _eec.delete_arrayDouble2

# Register arrayDouble2 in _eec:
_eec.arrayDouble2_swigregister(arrayDouble2)

class arrayUnsigned3(object):
    r"""Proxy of C++ std::array< unsigned int,3 > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iterator = _swig_new_instance_method(_eec.arrayUnsigned3_iterator)
    def __iter__(self):
        return self.iterator()
    __nonzero__ = _swig_new_instance_method(_eec.arrayUnsigned3___nonzero__)
    __bool__ = _swig_new_instance_method(_eec.arrayUnsigned3___bool__)
    __len__ = _swig_new_instance_method(_eec.arrayUnsigned3___len__)
    __getslice__ = _swig_new_instance_method(_eec.arrayUnsigned3___getslice__)
    __setslice__ = _swig_new_instance_method(_eec.arrayUnsigned3___setslice__)
    __delslice__ = _swig_new_instance_method(_eec.arrayUnsigned3___delslice__)
    __delitem__ = _swig_new_instance_method(_eec.arrayUnsigned3___delitem__)
    __getitem__ = _swig_new_instance_method(_eec.arrayUnsigned3___getitem__)
    __setitem__ = _swig_new_instance_method(_eec.arrayUnsigned3___setitem__)

    def __init__(self, *args):
        r"""
        __init__(arrayUnsigned3 self) -> arrayUnsigned3
        __init__(arrayUnsigned3 self, arrayUnsigned3 other) -> arrayUnsigned3
        """
        _eec.arrayUnsigned3_swiginit(self, _eec.new_arrayUnsigned3(*args))
    empty = _swig_new_instance_method(_eec.arrayUnsigned3_empty)
    size = _swig_new_instance_method(_eec.arrayUnsigned3_size)
    swap = _swig_new_instance_method(_eec.arrayUnsigned3_swap)
    begin = _swig_new_instance_method(_eec.arrayUnsigned3_begin)
    end = _swig_new_instance_method(_eec.arrayUnsigned3_end)
    rbegin = _swig_new_instance_method(_eec.arrayUnsigned3_rbegin)
    rend = _swig_new_instance_method(_eec.arrayUnsigned3_rend)
    front = _swig_new_instance_method(_eec.arrayUnsigned3_front)
    back = _swig_new_instance_method(_eec.arrayUnsigned3_back)
    fill = _swig_new_instance_method(_eec.arrayUnsigned3_fill)
    __swig_destroy__ = _eec.delete_arrayUnsigned3

# Register arrayUnsigned3 in _eec:
_eec.arrayUnsigned3_swigregister(arrayUnsigned3)

class arrayUnsigned13(object):
    r"""Proxy of C++ std::array< unsigned int,13 > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iterator = _swig_new_instance_method(_eec.arrayUnsigned13_iterator)
    def __iter__(self):
        return self.iterator()
    __nonzero__ = _swig_new_instance_method(_eec.arrayUnsigned13___nonzero__)
    __bool__ = _swig_new_instance_method(_eec.arrayUnsigned13___bool__)
    __len__ = _swig_new_instance_method(_eec.arrayUnsigned13___len__)
    __getslice__ = _swig_new_instance_method(_eec.arrayUnsigned13___getslice__)
    __setslice__ = _swig_new_instance_method(_eec.arrayUnsigned13___setslice__)
    __delslice__ = _swig_new_instance_method(_eec.arrayUnsigned13___delslice__)
    __delitem__ = _swig_new_instance_method(_eec.arrayUnsigned13___delitem__)
    __getitem__ = _swig_new_instance_method(_eec.arrayUnsigned13___getitem__)
    __setitem__ = _swig_new_instance_method(_eec.arrayUnsigned13___setitem__)

    def __init__(self, *args):
        r"""
        __init__(arrayUnsigned13 self) -> arrayUnsigned13
        __init__(arrayUnsigned13 self, arrayUnsigned13 other) -> arrayUnsigned13
        """
        _eec.arrayUnsigned13_swiginit(self, _eec.new_arrayUnsigned13(*args))
    empty = _swig_new_instance_method(_eec.arrayUnsigned13_empty)
    size = _swig_new_instance_method(_eec.arrayUnsigned13_size)
    swap = _swig_new_instance_method(_eec.arrayUnsigned13_swap)
    begin = _swig_new_instance_method(_eec.arrayUnsigned13_begin)
    end = _swig_new_instance_method(_eec.arrayUnsigned13_end)
    rbegin = _swig_new_instance_method(_eec.arrayUnsigned13_rbegin)
    rend = _swig_new_instance_method(_eec.arrayUnsigned13_rend)
    front = _swig_new_instance_method(_eec.arrayUnsigned13_front)
    back = _swig_new_instance_method(_eec.arrayUnsigned13_back)
    fill = _swig_new_instance_method(_eec.arrayUnsigned13_fill)
    __swig_destroy__ = _eec.delete_arrayUnsigned13

# Register arrayUnsigned13 in _eec:
_eec.arrayUnsigned13_swigregister(arrayUnsigned13)

class arrayPairDoubleDouble(object):
    r"""Proxy of C++ std::array< std::array< double,2 >,3 > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iterator = _swig_new_instance_method(_eec.arrayPairDoubleDouble_iterator)
    def __iter__(self):
        return self.iterator()
    __nonzero__ = _swig_new_instance_method(_eec.arrayPairDoubleDouble___nonzero__)
    __bool__ = _swig_new_instance_method(_eec.arrayPairDoubleDouble___bool__)
    __len__ = _swig_new_instance_method(_eec.arrayPairDoubleDouble___len__)
    __getslice__ = _swig_new_instance_method(_eec.arrayPairDoubleDouble___getslice__)
    __setslice__ = _swig_new_instance_method(_eec.arrayPairDoubleDouble___setslice__)
    __delslice__ = _swig_new_instance_method(_eec.arrayPairDoubleDouble___delslice__)
    __delitem__ = _swig_new_instance_method(_eec.arrayPairDoubleDouble___delitem__)
    __getitem__ = _swig_new_instance_method(_eec.arrayPairDoubleDouble___getitem__)
    __setitem__ = _swig_new_instance_method(_eec.arrayPairDoubleDouble___setitem__)

    def __init__(self, *args):
        r"""
        __init__(arrayPairDoubleDouble self) -> arrayPairDoubleDouble
        __init__(arrayPairDoubleDouble self, arrayPairDoubleDouble other) -> arrayPairDoubleDouble
        """
        _eec.arrayPairDoubleDouble_swiginit(self, _eec.new_arrayPairDoubleDouble(*args))
    empty = _swig_new_instance_method(_eec.arrayPairDoubleDouble_empty)
    size = _swig_new_instance_method(_eec.arrayPairDoubleDouble_size)
    swap = _swig_new_instance_method(_eec.arrayPairDoubleDouble_swap)
    begin = _swig_new_instance_method(_eec.arrayPairDoubleDouble_begin)
    end = _swig_new_instance_method(_eec.arrayPairDoubleDouble_end)
    rbegin = _swig_new_instance_method(_eec.arrayPairDoubleDouble_rbegin)
    rend = _swig_new_instance_method(_eec.arrayPairDoubleDouble_rend)
    front = _swig_new_instance_method(_eec.arrayPairDoubleDouble_front)
    back = _swig_new_instance_method(_eec.arrayPairDoubleDouble_back)
    fill = _swig_new_instance_method(_eec.arrayPairDoubleDouble_fill)
    __swig_destroy__ = _eec.delete_arrayPairDoubleDouble

# Register arrayPairDoubleDouble in _eec:
_eec.arrayPairDoubleDouble_swigregister(arrayPairDoubleDouble)

class vectorDouble(object):
    r"""Proxy of C++ std::vector< double > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iterator = _swig_new_instance_method(_eec.vectorDouble_iterator)
    def __iter__(self):
        return self.iterator()
    __nonzero__ = _swig_new_instance_method(_eec.vectorDouble___nonzero__)
    __bool__ = _swig_new_instance_method(_eec.vectorDouble___bool__)
    __len__ = _swig_new_instance_method(_eec.vectorDouble___len__)
    __getslice__ = _swig_new_instance_method(_eec.vectorDouble___getslice__)
    __setslice__ = _swig_new_instance_method(_eec.vectorDouble___setslice__)
    __delslice__ = _swig_new_instance_method(_eec.vectorDouble___delslice__)
    __delitem__ = _swig_new_instance_method(_eec.vectorDouble___delitem__)
    __getitem__ = _swig_new_instance_method(_eec.vectorDouble___getitem__)
    __setitem__ = _swig_new_instance_method(_eec.vectorDouble___setitem__)
    pop = _swig_new_instance_method(_eec.vectorDouble_pop)
    append = _swig_new_instance_method(_eec.vectorDouble_append)
    empty = _swig_new_instance_method(_eec.vectorDouble_empty)
    size = _swig_new_instance_method(_eec.vectorDouble_size)
    swap = _swig_new_instance_method(_eec.vectorDouble_swap)
    begin = _swig_new_instance_method(_eec.vectorDouble_begin)
    end = _swig_new_instance_method(_eec.vectorDouble_end)
    rbegin = _swig_new_instance_method(_eec.vectorDouble_rbegin)
    rend = _swig_new_instance_method(_eec.vectorDouble_rend)
    clear = _swig_new_instance_method(_eec.vectorDouble_clear)
    get_allocator = _swig_new_instance_method(_eec.vectorDouble_get_allocator)
    pop_back = _swig_new_instance_method(_eec.vectorDouble_pop_back)
    erase = _swig_new_instance_method(_eec.vectorDouble_erase)

    def __init__(self, *args):
        r"""
        __init__(vectorDouble self) -> vectorDouble
        __init__(vectorDouble self, vectorDouble other) -> vectorDouble
        __init__(vectorDouble self, std::vector< double >::size_type size) -> vectorDouble
        __init__(vectorDouble self, std::vector< double >::size_type size, std::vector< double >::value_type const & value) -> vectorDouble
        """
        _eec.vectorDouble_swiginit(self, _eec.new_vectorDouble(*args))
    push_back = _swig_new_instance_method(_eec.vectorDouble_push_back)
    front = _swig_new_instance_method(_eec.vectorDouble_front)
    back = _swig_new_instance_method(_eec.vectorDouble_back)
    assign = _swig_new_instance_method(_eec.vectorDouble_assign)
    resize = _swig_new_instance_method(_eec.vectorDouble_resize)
    insert = _swig_new_instance_method(_eec.vectorDouble_insert)
    reserve = _swig_new_instance_method(_eec.vectorDouble_reserve)
    capacity = _swig_new_instance_method(_eec.vectorDouble_capacity)
    __swig_destroy__ = _eec.delete_vectorDouble

# Register vectorDouble in _eec:
_eec.vectorDouble_swigregister(vectorDouble)

class vectorUnsigned(object):
    r"""Proxy of C++ std::vector< unsigned int > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iterator = _swig_new_instance_method(_eec.vectorUnsigned_iterator)
    def __iter__(self):
        return self.iterator()
    __nonzero__ = _swig_new_instance_method(_eec.vectorUnsigned___nonzero__)
    __bool__ = _swig_new_instance_method(_eec.vectorUnsigned___bool__)
    __len__ = _swig_new_instance_method(_eec.vectorUnsigned___len__)
    __getslice__ = _swig_new_instance_method(_eec.vectorUnsigned___getslice__)
    __setslice__ = _swig_new_instance_method(_eec.vectorUnsigned___setslice__)
    __delslice__ = _swig_new_instance_method(_eec.vectorUnsigned___delslice__)
    __delitem__ = _swig_new_instance_method(_eec.vectorUnsigned___delitem__)
    __getitem__ = _swig_new_instance_method(_eec.vectorUnsigned___getitem__)
    __setitem__ = _swig_new_instance_method(_eec.vectorUnsigned___setitem__)
    pop = _swig_new_instance_method(_eec.vectorUnsigned_pop)
    append = _swig_new_instance_method(_eec.vectorUnsigned_append)
    empty = _swig_new_instance_method(_eec.vectorUnsigned_empty)
    size = _swig_new_instance_method(_eec.vectorUnsigned_size)
    swap = _swig_new_instance_method(_eec.vectorUnsigned_swap)
    begin = _swig_new_instance_method(_eec.vectorUnsigned_begin)
    end = _swig_new_instance_method(_eec.vectorUnsigned_end)
    rbegin = _swig_new_instance_method(_eec.vectorUnsigned_rbegin)
    rend = _swig_new_instance_method(_eec.vectorUnsigned_rend)
    clear = _swig_new_instance_method(_eec.vectorUnsigned_clear)
    get_allocator = _swig_new_instance_method(_eec.vectorUnsigned_get_allocator)
    pop_back = _swig_new_instance_method(_eec.vectorUnsigned_pop_back)
    erase = _swig_new_instance_method(_eec.vectorUnsigned_erase)

    def __init__(self, *args):
        r"""
        __init__(vectorUnsigned self) -> vectorUnsigned
        __init__(vectorUnsigned self, vectorUnsigned other) -> vectorUnsigned
        __init__(vectorUnsigned self, std::vector< unsigned int >::size_type size) -> vectorUnsigned
        __init__(vectorUnsigned self, std::vector< unsigned int >::size_type size, std::vector< unsigned int >::value_type const & value) -> vectorUnsigned
        """
        _eec.vectorUnsigned_swiginit(self, _eec.new_vectorUnsigned(*args))
    push_back = _swig_new_instance_method(_eec.vectorUnsigned_push_back)
    front = _swig_new_instance_method(_eec.vectorUnsigned_front)
    back = _swig_new_instance_method(_eec.vectorUnsigned_back)
    assign = _swig_new_instance_method(_eec.vectorUnsigned_assign)
    resize = _swig_new_instance_method(_eec.vectorUnsigned_resize)
    insert = _swig_new_instance_method(_eec.vectorUnsigned_insert)
    reserve = _swig_new_instance_method(_eec.vectorUnsigned_reserve)
    capacity = _swig_new_instance_method(_eec.vectorUnsigned_capacity)
    __swig_destroy__ = _eec.delete_vectorUnsigned

# Register vectorUnsigned in _eec:
_eec.vectorUnsigned_swigregister(vectorUnsigned)

class vectorArrayDouble2(object):
    r"""Proxy of C++ std::vector< std::array< double,2 > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iterator = _swig_new_instance_method(_eec.vectorArrayDouble2_iterator)
    def __iter__(self):
        return self.iterator()
    __nonzero__ = _swig_new_instance_method(_eec.vectorArrayDouble2___nonzero__)
    __bool__ = _swig_new_instance_method(_eec.vectorArrayDouble2___bool__)
    __len__ = _swig_new_instance_method(_eec.vectorArrayDouble2___len__)
    __getslice__ = _swig_new_instance_method(_eec.vectorArrayDouble2___getslice__)
    __setslice__ = _swig_new_instance_method(_eec.vectorArrayDouble2___setslice__)
    __delslice__ = _swig_new_instance_method(_eec.vectorArrayDouble2___delslice__)
    __delitem__ = _swig_new_instance_method(_eec.vectorArrayDouble2___delitem__)
    __getitem__ = _swig_new_instance_method(_eec.vectorArrayDouble2___getitem__)
    __setitem__ = _swig_new_instance_method(_eec.vectorArrayDouble2___setitem__)
    pop = _swig_new_instance_method(_eec.vectorArrayDouble2_pop)
    append = _swig_new_instance_method(_eec.vectorArrayDouble2_append)
    empty = _swig_new_instance_method(_eec.vectorArrayDouble2_empty)
    size = _swig_new_instance_method(_eec.vectorArrayDouble2_size)
    swap = _swig_new_instance_method(_eec.vectorArrayDouble2_swap)
    begin = _swig_new_instance_method(_eec.vectorArrayDouble2_begin)
    end = _swig_new_instance_method(_eec.vectorArrayDouble2_end)
    rbegin = _swig_new_instance_method(_eec.vectorArrayDouble2_rbegin)
    rend = _swig_new_instance_method(_eec.vectorArrayDouble2_rend)
    clear = _swig_new_instance_method(_eec.vectorArrayDouble2_clear)
    get_allocator = _swig_new_instance_method(_eec.vectorArrayDouble2_get_allocator)
    pop_back = _swig_new_instance_method(_eec.vectorArrayDouble2_pop_back)
    erase = _swig_new_instance_method(_eec.vectorArrayDouble2_erase)

    def __init__(self, *args):
        r"""
        __init__(vectorArrayDouble2 self) -> vectorArrayDouble2
        __init__(vectorArrayDouble2 self, vectorArrayDouble2 other) -> vectorArrayDouble2
        __init__(vectorArrayDouble2 self, std::vector< std::array< double,2 > >::size_type size) -> vectorArrayDouble2
        __init__(vectorArrayDouble2 self, std::vector< std::array< double,2 > >::size_type size, arrayDouble2 value) -> vectorArrayDouble2
        """
        _eec.vectorArrayDouble2_swiginit(self, _eec.new_vectorArrayDouble2(*args))
    push_back = _swig_new_instance_method(_eec.vectorArrayDouble2_push_back)
    front = _swig_new_instance_method(_eec.vectorArrayDouble2_front)
    back = _swig_new_instance_method(_eec.vectorArrayDouble2_back)
    assign = _swig_new_instance_method(_eec.vectorArrayDouble2_assign)
    resize = _swig_new_instance_method(_eec.vectorArrayDouble2_resize)
    insert = _swig_new_instance_method(_eec.vectorArrayDouble2_insert)
    reserve = _swig_new_instance_method(_eec.vectorArrayDouble2_reserve)
    capacity = _swig_new_instance_method(_eec.vectorArrayDouble2_capacity)
    __swig_destroy__ = _eec.delete_vectorArrayDouble2

# Register vectorArrayDouble2 in _eec:
_eec.vectorArrayDouble2_swigregister(vectorArrayDouble2)

ParticleWeight_TransverseMomentum = _eec.ParticleWeight_TransverseMomentum

ParticleWeight_Energy = _eec.ParticleWeight_Energy

ParticleWeight_TransverseEnergy = _eec.ParticleWeight_TransverseEnergy

ParticleWeight_Momentum = _eec.ParticleWeight_Momentum

PairwiseDistance_DeltaR = _eec.PairwiseDistance_DeltaR

PairwiseDistance_HadronicDot = _eec.PairwiseDistance_HadronicDot

PairwiseDistance_EEDot = _eec.PairwiseDistance_EEDot

PairwiseDistance_HadronicDotMassive = _eec.PairwiseDistance_HadronicDotMassive

PairwiseDistance_EEDotMassless = _eec.PairwiseDistance_EEDotMassless

PairwiseDistance_EEArcLength = _eec.PairwiseDistance_EEArcLength

PairwiseDistance_EEArcLengthMassive = _eec.PairwiseDistance_EEArcLengthMassive

PairwiseDistance_EECosTheta = _eec.PairwiseDistance_EECosTheta

PairwiseDistance_EECosThetaMassive = _eec.PairwiseDistance_EECosThetaMassive

ArchiveFormat_Text = _eec.ArchiveFormat_Text

ArchiveFormat_Binary = _eec.ArchiveFormat_Binary

ArchiveFormat_NotSupported = _eec.ArchiveFormat_NotSupported

CompressionMode_Auto = _eec.CompressionMode_Auto

CompressionMode_Plain = _eec.CompressionMode_Plain

CompressionMode_Zlib = _eec.CompressionMode_Zlib

CompressionMode_NotSupported = _eec.CompressionMode_NotSupported

get_archive_format = _eec.get_archive_format
get_compression_mode = _eec.get_compression_mode
set_archive_format = _eec.set_archive_format
set_compression_mode = _eec.set_compression_mode
particle_weight_name = _eec.particle_weight_name
pairwise_distance_name = _eec.pairwise_distance_name
class reduce_command(object):
    r"""Proxy of C++ boost::histogram::algorithm::reduce_command class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(reduce_command self) -> reduce_command"""
        _eec.reduce_command_swiginit(self, _eec.new_reduce_command())
    __swig_destroy__ = _eec.delete_reduce_command

# Register reduce_command in _eec:
_eec.reduce_command_swigregister(reduce_command)
cvar = _eec.cvar
REG = cvar.REG
PI = cvar.PI
TWOPI = cvar.TWOPI
HAS_SERIALIZATION_SUPPORT = cvar.HAS_SERIALIZATION_SUPPORT

rebin = _eec.rebin
shrink = _eec.shrink
slice = _eec.slice
shrink_and_rebin = _eec.shrink_and_rebin
slice_and_rebin = _eec.slice_and_rebin
class vectorReduceCommand(object):
    r"""Proxy of C++ std::vector< boost::histogram::algorithm::reduce_command > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iterator = _swig_new_instance_method(_eec.vectorReduceCommand_iterator)
    def __iter__(self):
        return self.iterator()
    __nonzero__ = _swig_new_instance_method(_eec.vectorReduceCommand___nonzero__)
    __bool__ = _swig_new_instance_method(_eec.vectorReduceCommand___bool__)
    __len__ = _swig_new_instance_method(_eec.vectorReduceCommand___len__)
    __getslice__ = _swig_new_instance_method(_eec.vectorReduceCommand___getslice__)
    __setslice__ = _swig_new_instance_method(_eec.vectorReduceCommand___setslice__)
    __delslice__ = _swig_new_instance_method(_eec.vectorReduceCommand___delslice__)
    __delitem__ = _swig_new_instance_method(_eec.vectorReduceCommand___delitem__)
    __getitem__ = _swig_new_instance_method(_eec.vectorReduceCommand___getitem__)
    __setitem__ = _swig_new_instance_method(_eec.vectorReduceCommand___setitem__)
    pop = _swig_new_instance_method(_eec.vectorReduceCommand_pop)
    append = _swig_new_instance_method(_eec.vectorReduceCommand_append)
    empty = _swig_new_instance_method(_eec.vectorReduceCommand_empty)
    size = _swig_new_instance_method(_eec.vectorReduceCommand_size)
    swap = _swig_new_instance_method(_eec.vectorReduceCommand_swap)
    begin = _swig_new_instance_method(_eec.vectorReduceCommand_begin)
    end = _swig_new_instance_method(_eec.vectorReduceCommand_end)
    rbegin = _swig_new_instance_method(_eec.vectorReduceCommand_rbegin)
    rend = _swig_new_instance_method(_eec.vectorReduceCommand_rend)
    clear = _swig_new_instance_method(_eec.vectorReduceCommand_clear)
    get_allocator = _swig_new_instance_method(_eec.vectorReduceCommand_get_allocator)
    pop_back = _swig_new_instance_method(_eec.vectorReduceCommand_pop_back)
    erase = _swig_new_instance_method(_eec.vectorReduceCommand_erase)

    def __init__(self, *args):
        r"""
        __init__(vectorReduceCommand self) -> vectorReduceCommand
        __init__(vectorReduceCommand self, vectorReduceCommand other) -> vectorReduceCommand
        __init__(vectorReduceCommand self, std::vector< boost::histogram::algorithm::reduce_command >::size_type size) -> vectorReduceCommand
        __init__(vectorReduceCommand self, std::vector< boost::histogram::algorithm::reduce_command >::size_type size, reduce_command value) -> vectorReduceCommand
        """
        _eec.vectorReduceCommand_swiginit(self, _eec.new_vectorReduceCommand(*args))
    push_back = _swig_new_instance_method(_eec.vectorReduceCommand_push_back)
    front = _swig_new_instance_method(_eec.vectorReduceCommand_front)
    back = _swig_new_instance_method(_eec.vectorReduceCommand_back)
    assign = _swig_new_instance_method(_eec.vectorReduceCommand_assign)
    resize = _swig_new_instance_method(_eec.vectorReduceCommand_resize)
    insert = _swig_new_instance_method(_eec.vectorReduceCommand_insert)
    reserve = _swig_new_instance_method(_eec.vectorReduceCommand_reserve)
    capacity = _swig_new_instance_method(_eec.vectorReduceCommand_capacity)
    __swig_destroy__ = _eec.delete_vectorReduceCommand

# Register vectorReduceCommand in _eec:
_eec.vectorReduceCommand_swigregister(vectorReduceCommand)

class EECHistBase1DId(object):
    r"""Proxy of C++ fastjet::contrib::eec::hist::EECHistBase< fastjet::contrib::eec::hist::EECHist1D< axis::id > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    rank = _swig_new_static_method(_eec.EECHistBase1DId_rank)
    __swig_destroy__ = _eec.delete_EECHistBase1DId
    track_covariance = _swig_new_instance_method(_eec.EECHistBase1DId_track_covariance)
    variance_bound = _swig_new_instance_method(_eec.EECHistBase1DId_variance_bound)
    variance_bound_includes_overflows = _swig_new_instance_method(_eec.EECHistBase1DId_variance_bound_includes_overflows)
    nhists = _swig_new_instance_method(_eec.EECHistBase1DId_nhists)
    nbins = _swig_new_instance_method(_eec.EECHistBase1DId_nbins)
    axis_range = _swig_new_instance_method(_eec.EECHistBase1DId_axis_range)
    axis_min = _swig_new_instance_method(_eec.EECHistBase1DId_axis_min)
    axis_max = _swig_new_instance_method(_eec.EECHistBase1DId_axis_max)
    set_track_covariance = _swig_new_instance_method(_eec.EECHistBase1DId_set_track_covariance)
    set_variance_bound = _swig_new_instance_method(_eec.EECHistBase1DId_set_variance_bound)
    set_variance_bound_includes_overflows = _swig_new_instance_method(_eec.EECHistBase1DId_set_variance_bound_includes_overflows)
    set_nbins = _swig_new_instance_method(_eec.EECHistBase1DId_set_nbins)
    set_axis_range = _swig_new_instance_method(_eec.EECHistBase1DId_set_axis_range)
    set_axes_range = _swig_new_instance_method(_eec.EECHistBase1DId_set_axes_range)
    bin_centers_vec = _swig_new_instance_method(_eec.EECHistBase1DId_bin_centers_vec)
    bin_edges_vec = _swig_new_instance_method(_eec.EECHistBase1DId_bin_edges_vec)
    hist_size = _swig_new_instance_method(_eec.EECHistBase1DId_hist_size)
    covariance_size = _swig_new_instance_method(_eec.EECHistBase1DId_covariance_size)
    event_counter = _swig_new_instance_method(_eec.EECHistBase1DId_event_counter)
    reduce = _swig_new_instance_method(_eec.EECHistBase1DId_reduce)
    sum = _swig_new_instance_method(_eec.EECHistBase1DId_sum)
    diff_hists = _swig_new_instance_method(_eec.EECHistBase1DId_diff_hists)
    diff_covariances = _swig_new_instance_method(_eec.EECHistBase1DId_diff_covariances)
    diff_variance_bounds = _swig_new_instance_method(_eec.EECHistBase1DId_diff_variance_bounds)
    __ne__ = _swig_new_instance_method(_eec.EECHistBase1DId___ne__)
    __eq__ = _swig_new_instance_method(_eec.EECHistBase1DId___eq__)
    hists_as_text = _swig_new_instance_method(_eec.EECHistBase1DId_hists_as_text)
    bin_centers = _swig_new_instance_method(_eec.EECHistBase1DId_bin_centers)
    bin_edges = _swig_new_instance_method(_eec.EECHistBase1DId_bin_edges)
    scale = _swig_new_instance_method(_eec.EECHistBase1DId_scale)

    def get_hist_errs(self, hist_i=0, overflows=True):
        hist, vars = self.get_hist_vars(hist_i, overflows)
        return hist, _np.sqrt(vars)

    def get_error_bound(self, hist_i=0, overflows=True):
        return _np.sqrt(self.get_variance_bound(hist_i, overflows))


# Register EECHistBase1DId in _eec:
_eec.EECHistBase1DId_swigregister(EECHistBase1DId)
EECHistBase1DId_rank = _eec.EECHistBase1DId_rank

class EECHistBase1DLog(object):
    r"""Proxy of C++ fastjet::contrib::eec::hist::EECHistBase< fastjet::contrib::eec::hist::EECHist1D< axis::log > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    rank = _swig_new_static_method(_eec.EECHistBase1DLog_rank)
    __swig_destroy__ = _eec.delete_EECHistBase1DLog
    track_covariance = _swig_new_instance_method(_eec.EECHistBase1DLog_track_covariance)
    variance_bound = _swig_new_instance_method(_eec.EECHistBase1DLog_variance_bound)
    variance_bound_includes_overflows = _swig_new_instance_method(_eec.EECHistBase1DLog_variance_bound_includes_overflows)
    nhists = _swig_new_instance_method(_eec.EECHistBase1DLog_nhists)
    nbins = _swig_new_instance_method(_eec.EECHistBase1DLog_nbins)
    axis_range = _swig_new_instance_method(_eec.EECHistBase1DLog_axis_range)
    axis_min = _swig_new_instance_method(_eec.EECHistBase1DLog_axis_min)
    axis_max = _swig_new_instance_method(_eec.EECHistBase1DLog_axis_max)
    set_track_covariance = _swig_new_instance_method(_eec.EECHistBase1DLog_set_track_covariance)
    set_variance_bound = _swig_new_instance_method(_eec.EECHistBase1DLog_set_variance_bound)
    set_variance_bound_includes_overflows = _swig_new_instance_method(_eec.EECHistBase1DLog_set_variance_bound_includes_overflows)
    set_nbins = _swig_new_instance_method(_eec.EECHistBase1DLog_set_nbins)
    set_axis_range = _swig_new_instance_method(_eec.EECHistBase1DLog_set_axis_range)
    set_axes_range = _swig_new_instance_method(_eec.EECHistBase1DLog_set_axes_range)
    bin_centers_vec = _swig_new_instance_method(_eec.EECHistBase1DLog_bin_centers_vec)
    bin_edges_vec = _swig_new_instance_method(_eec.EECHistBase1DLog_bin_edges_vec)
    hist_size = _swig_new_instance_method(_eec.EECHistBase1DLog_hist_size)
    covariance_size = _swig_new_instance_method(_eec.EECHistBase1DLog_covariance_size)
    event_counter = _swig_new_instance_method(_eec.EECHistBase1DLog_event_counter)
    reduce = _swig_new_instance_method(_eec.EECHistBase1DLog_reduce)
    sum = _swig_new_instance_method(_eec.EECHistBase1DLog_sum)
    diff_hists = _swig_new_instance_method(_eec.EECHistBase1DLog_diff_hists)
    diff_covariances = _swig_new_instance_method(_eec.EECHistBase1DLog_diff_covariances)
    diff_variance_bounds = _swig_new_instance_method(_eec.EECHistBase1DLog_diff_variance_bounds)
    __ne__ = _swig_new_instance_method(_eec.EECHistBase1DLog___ne__)
    __eq__ = _swig_new_instance_method(_eec.EECHistBase1DLog___eq__)
    hists_as_text = _swig_new_instance_method(_eec.EECHistBase1DLog_hists_as_text)
    bin_centers = _swig_new_instance_method(_eec.EECHistBase1DLog_bin_centers)
    bin_edges = _swig_new_instance_method(_eec.EECHistBase1DLog_bin_edges)
    scale = _swig_new_instance_method(_eec.EECHistBase1DLog_scale)

    def get_hist_errs(self, hist_i=0, overflows=True):
        hist, vars = self.get_hist_vars(hist_i, overflows)
        return hist, _np.sqrt(vars)

    def get_error_bound(self, hist_i=0, overflows=True):
        return _np.sqrt(self.get_variance_bound(hist_i, overflows))


# Register EECHistBase1DLog in _eec:
_eec.EECHistBase1DLog_swigregister(EECHistBase1DLog)
EECHistBase1DLog_rank = _eec.EECHistBase1DLog_rank

class EECHistBaseIdIdId(object):
    r"""Proxy of C++ fastjet::contrib::eec::hist::EECHistBase< fastjet::contrib::eec::hist::EECHist3D< axis::id,axis::id,axis::id > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    rank = _swig_new_static_method(_eec.EECHistBaseIdIdId_rank)
    __swig_destroy__ = _eec.delete_EECHistBaseIdIdId
    track_covariance = _swig_new_instance_method(_eec.EECHistBaseIdIdId_track_covariance)
    variance_bound = _swig_new_instance_method(_eec.EECHistBaseIdIdId_variance_bound)
    variance_bound_includes_overflows = _swig_new_instance_method(_eec.EECHistBaseIdIdId_variance_bound_includes_overflows)
    nhists = _swig_new_instance_method(_eec.EECHistBaseIdIdId_nhists)
    nbins = _swig_new_instance_method(_eec.EECHistBaseIdIdId_nbins)
    axis_range = _swig_new_instance_method(_eec.EECHistBaseIdIdId_axis_range)
    axis_min = _swig_new_instance_method(_eec.EECHistBaseIdIdId_axis_min)
    axis_max = _swig_new_instance_method(_eec.EECHistBaseIdIdId_axis_max)
    set_track_covariance = _swig_new_instance_method(_eec.EECHistBaseIdIdId_set_track_covariance)
    set_variance_bound = _swig_new_instance_method(_eec.EECHistBaseIdIdId_set_variance_bound)
    set_variance_bound_includes_overflows = _swig_new_instance_method(_eec.EECHistBaseIdIdId_set_variance_bound_includes_overflows)
    set_nbins = _swig_new_instance_method(_eec.EECHistBaseIdIdId_set_nbins)
    set_axis_range = _swig_new_instance_method(_eec.EECHistBaseIdIdId_set_axis_range)
    set_axes_range = _swig_new_instance_method(_eec.EECHistBaseIdIdId_set_axes_range)
    bin_centers_vec = _swig_new_instance_method(_eec.EECHistBaseIdIdId_bin_centers_vec)
    bin_edges_vec = _swig_new_instance_method(_eec.EECHistBaseIdIdId_bin_edges_vec)
    hist_size = _swig_new_instance_method(_eec.EECHistBaseIdIdId_hist_size)
    covariance_size = _swig_new_instance_method(_eec.EECHistBaseIdIdId_covariance_size)
    event_counter = _swig_new_instance_method(_eec.EECHistBaseIdIdId_event_counter)
    reduce = _swig_new_instance_method(_eec.EECHistBaseIdIdId_reduce)
    sum = _swig_new_instance_method(_eec.EECHistBaseIdIdId_sum)
    diff_hists = _swig_new_instance_method(_eec.EECHistBaseIdIdId_diff_hists)
    diff_covariances = _swig_new_instance_method(_eec.EECHistBaseIdIdId_diff_covariances)
    diff_variance_bounds = _swig_new_instance_method(_eec.EECHistBaseIdIdId_diff_variance_bounds)
    __ne__ = _swig_new_instance_method(_eec.EECHistBaseIdIdId___ne__)
    __eq__ = _swig_new_instance_method(_eec.EECHistBaseIdIdId___eq__)
    hists_as_text = _swig_new_instance_method(_eec.EECHistBaseIdIdId_hists_as_text)
    bin_centers = _swig_new_instance_method(_eec.EECHistBaseIdIdId_bin_centers)
    bin_edges = _swig_new_instance_method(_eec.EECHistBaseIdIdId_bin_edges)
    scale = _swig_new_instance_method(_eec.EECHistBaseIdIdId_scale)

    def get_hist_errs(self, hist_i=0, overflows=True):
        hist, vars = self.get_hist_vars(hist_i, overflows)
        return hist, _np.sqrt(vars)

    def get_error_bound(self, hist_i=0, overflows=True):
        return _np.sqrt(self.get_variance_bound(hist_i, overflows))


# Register EECHistBaseIdIdId in _eec:
_eec.EECHistBaseIdIdId_swigregister(EECHistBaseIdIdId)
EECHistBaseIdIdId_rank = _eec.EECHistBaseIdIdId_rank

class EECHistBaseLogIdId(object):
    r"""Proxy of C++ fastjet::contrib::eec::hist::EECHistBase< fastjet::contrib::eec::hist::EECHist3D< axis::log,axis::id,axis::id > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    rank = _swig_new_static_method(_eec.EECHistBaseLogIdId_rank)
    __swig_destroy__ = _eec.delete_EECHistBaseLogIdId
    track_covariance = _swig_new_instance_method(_eec.EECHistBaseLogIdId_track_covariance)
    variance_bound = _swig_new_instance_method(_eec.EECHistBaseLogIdId_variance_bound)
    variance_bound_includes_overflows = _swig_new_instance_method(_eec.EECHistBaseLogIdId_variance_bound_includes_overflows)
    nhists = _swig_new_instance_method(_eec.EECHistBaseLogIdId_nhists)
    nbins = _swig_new_instance_method(_eec.EECHistBaseLogIdId_nbins)
    axis_range = _swig_new_instance_method(_eec.EECHistBaseLogIdId_axis_range)
    axis_min = _swig_new_instance_method(_eec.EECHistBaseLogIdId_axis_min)
    axis_max = _swig_new_instance_method(_eec.EECHistBaseLogIdId_axis_max)
    set_track_covariance = _swig_new_instance_method(_eec.EECHistBaseLogIdId_set_track_covariance)
    set_variance_bound = _swig_new_instance_method(_eec.EECHistBaseLogIdId_set_variance_bound)
    set_variance_bound_includes_overflows = _swig_new_instance_method(_eec.EECHistBaseLogIdId_set_variance_bound_includes_overflows)
    set_nbins = _swig_new_instance_method(_eec.EECHistBaseLogIdId_set_nbins)
    set_axis_range = _swig_new_instance_method(_eec.EECHistBaseLogIdId_set_axis_range)
    set_axes_range = _swig_new_instance_method(_eec.EECHistBaseLogIdId_set_axes_range)
    bin_centers_vec = _swig_new_instance_method(_eec.EECHistBaseLogIdId_bin_centers_vec)
    bin_edges_vec = _swig_new_instance_method(_eec.EECHistBaseLogIdId_bin_edges_vec)
    hist_size = _swig_new_instance_method(_eec.EECHistBaseLogIdId_hist_size)
    covariance_size = _swig_new_instance_method(_eec.EECHistBaseLogIdId_covariance_size)
    event_counter = _swig_new_instance_method(_eec.EECHistBaseLogIdId_event_counter)
    reduce = _swig_new_instance_method(_eec.EECHistBaseLogIdId_reduce)
    sum = _swig_new_instance_method(_eec.EECHistBaseLogIdId_sum)
    diff_hists = _swig_new_instance_method(_eec.EECHistBaseLogIdId_diff_hists)
    diff_covariances = _swig_new_instance_method(_eec.EECHistBaseLogIdId_diff_covariances)
    diff_variance_bounds = _swig_new_instance_method(_eec.EECHistBaseLogIdId_diff_variance_bounds)
    __ne__ = _swig_new_instance_method(_eec.EECHistBaseLogIdId___ne__)
    __eq__ = _swig_new_instance_method(_eec.EECHistBaseLogIdId___eq__)
    hists_as_text = _swig_new_instance_method(_eec.EECHistBaseLogIdId_hists_as_text)
    bin_centers = _swig_new_instance_method(_eec.EECHistBaseLogIdId_bin_centers)
    bin_edges = _swig_new_instance_method(_eec.EECHistBaseLogIdId_bin_edges)
    scale = _swig_new_instance_method(_eec.EECHistBaseLogIdId_scale)

    def get_hist_errs(self, hist_i=0, overflows=True):
        hist, vars = self.get_hist_vars(hist_i, overflows)
        return hist, _np.sqrt(vars)

    def get_error_bound(self, hist_i=0, overflows=True):
        return _np.sqrt(self.get_variance_bound(hist_i, overflows))


# Register EECHistBaseLogIdId in _eec:
_eec.EECHistBaseLogIdId_swigregister(EECHistBaseLogIdId)
EECHistBaseLogIdId_rank = _eec.EECHistBaseLogIdId_rank

class EECHistBaseIdLogId(object):
    r"""Proxy of C++ fastjet::contrib::eec::hist::EECHistBase< fastjet::contrib::eec::hist::EECHist3D< axis::id,axis::log,axis::id > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    rank = _swig_new_static_method(_eec.EECHistBaseIdLogId_rank)
    __swig_destroy__ = _eec.delete_EECHistBaseIdLogId
    track_covariance = _swig_new_instance_method(_eec.EECHistBaseIdLogId_track_covariance)
    variance_bound = _swig_new_instance_method(_eec.EECHistBaseIdLogId_variance_bound)
    variance_bound_includes_overflows = _swig_new_instance_method(_eec.EECHistBaseIdLogId_variance_bound_includes_overflows)
    nhists = _swig_new_instance_method(_eec.EECHistBaseIdLogId_nhists)
    nbins = _swig_new_instance_method(_eec.EECHistBaseIdLogId_nbins)
    axis_range = _swig_new_instance_method(_eec.EECHistBaseIdLogId_axis_range)
    axis_min = _swig_new_instance_method(_eec.EECHistBaseIdLogId_axis_min)
    axis_max = _swig_new_instance_method(_eec.EECHistBaseIdLogId_axis_max)
    set_track_covariance = _swig_new_instance_method(_eec.EECHistBaseIdLogId_set_track_covariance)
    set_variance_bound = _swig_new_instance_method(_eec.EECHistBaseIdLogId_set_variance_bound)
    set_variance_bound_includes_overflows = _swig_new_instance_method(_eec.EECHistBaseIdLogId_set_variance_bound_includes_overflows)
    set_nbins = _swig_new_instance_method(_eec.EECHistBaseIdLogId_set_nbins)
    set_axis_range = _swig_new_instance_method(_eec.EECHistBaseIdLogId_set_axis_range)
    set_axes_range = _swig_new_instance_method(_eec.EECHistBaseIdLogId_set_axes_range)
    bin_centers_vec = _swig_new_instance_method(_eec.EECHistBaseIdLogId_bin_centers_vec)
    bin_edges_vec = _swig_new_instance_method(_eec.EECHistBaseIdLogId_bin_edges_vec)
    hist_size = _swig_new_instance_method(_eec.EECHistBaseIdLogId_hist_size)
    covariance_size = _swig_new_instance_method(_eec.EECHistBaseIdLogId_covariance_size)
    event_counter = _swig_new_instance_method(_eec.EECHistBaseIdLogId_event_counter)
    reduce = _swig_new_instance_method(_eec.EECHistBaseIdLogId_reduce)
    sum = _swig_new_instance_method(_eec.EECHistBaseIdLogId_sum)
    diff_hists = _swig_new_instance_method(_eec.EECHistBaseIdLogId_diff_hists)
    diff_covariances = _swig_new_instance_method(_eec.EECHistBaseIdLogId_diff_covariances)
    diff_variance_bounds = _swig_new_instance_method(_eec.EECHistBaseIdLogId_diff_variance_bounds)
    __ne__ = _swig_new_instance_method(_eec.EECHistBaseIdLogId___ne__)
    __eq__ = _swig_new_instance_method(_eec.EECHistBaseIdLogId___eq__)
    hists_as_text = _swig_new_instance_method(_eec.EECHistBaseIdLogId_hists_as_text)
    bin_centers = _swig_new_instance_method(_eec.EECHistBaseIdLogId_bin_centers)
    bin_edges = _swig_new_instance_method(_eec.EECHistBaseIdLogId_bin_edges)
    scale = _swig_new_instance_method(_eec.EECHistBaseIdLogId_scale)

    def get_hist_errs(self, hist_i=0, overflows=True):
        hist, vars = self.get_hist_vars(hist_i, overflows)
        return hist, _np.sqrt(vars)

    def get_error_bound(self, hist_i=0, overflows=True):
        return _np.sqrt(self.get_variance_bound(hist_i, overflows))


# Register EECHistBaseIdLogId in _eec:
_eec.EECHistBaseIdLogId_swigregister(EECHistBaseIdLogId)
EECHistBaseIdLogId_rank = _eec.EECHistBaseIdLogId_rank

class EECHistBaseLogLogId(object):
    r"""Proxy of C++ fastjet::contrib::eec::hist::EECHistBase< fastjet::contrib::eec::hist::EECHist3D< axis::log,axis::log,axis::id > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    rank = _swig_new_static_method(_eec.EECHistBaseLogLogId_rank)
    __swig_destroy__ = _eec.delete_EECHistBaseLogLogId
    track_covariance = _swig_new_instance_method(_eec.EECHistBaseLogLogId_track_covariance)
    variance_bound = _swig_new_instance_method(_eec.EECHistBaseLogLogId_variance_bound)
    variance_bound_includes_overflows = _swig_new_instance_method(_eec.EECHistBaseLogLogId_variance_bound_includes_overflows)
    nhists = _swig_new_instance_method(_eec.EECHistBaseLogLogId_nhists)
    nbins = _swig_new_instance_method(_eec.EECHistBaseLogLogId_nbins)
    axis_range = _swig_new_instance_method(_eec.EECHistBaseLogLogId_axis_range)
    axis_min = _swig_new_instance_method(_eec.EECHistBaseLogLogId_axis_min)
    axis_max = _swig_new_instance_method(_eec.EECHistBaseLogLogId_axis_max)
    set_track_covariance = _swig_new_instance_method(_eec.EECHistBaseLogLogId_set_track_covariance)
    set_variance_bound = _swig_new_instance_method(_eec.EECHistBaseLogLogId_set_variance_bound)
    set_variance_bound_includes_overflows = _swig_new_instance_method(_eec.EECHistBaseLogLogId_set_variance_bound_includes_overflows)
    set_nbins = _swig_new_instance_method(_eec.EECHistBaseLogLogId_set_nbins)
    set_axis_range = _swig_new_instance_method(_eec.EECHistBaseLogLogId_set_axis_range)
    set_axes_range = _swig_new_instance_method(_eec.EECHistBaseLogLogId_set_axes_range)
    bin_centers_vec = _swig_new_instance_method(_eec.EECHistBaseLogLogId_bin_centers_vec)
    bin_edges_vec = _swig_new_instance_method(_eec.EECHistBaseLogLogId_bin_edges_vec)
    hist_size = _swig_new_instance_method(_eec.EECHistBaseLogLogId_hist_size)
    covariance_size = _swig_new_instance_method(_eec.EECHistBaseLogLogId_covariance_size)
    event_counter = _swig_new_instance_method(_eec.EECHistBaseLogLogId_event_counter)
    reduce = _swig_new_instance_method(_eec.EECHistBaseLogLogId_reduce)
    sum = _swig_new_instance_method(_eec.EECHistBaseLogLogId_sum)
    diff_hists = _swig_new_instance_method(_eec.EECHistBaseLogLogId_diff_hists)
    diff_covariances = _swig_new_instance_method(_eec.EECHistBaseLogLogId_diff_covariances)
    diff_variance_bounds = _swig_new_instance_method(_eec.EECHistBaseLogLogId_diff_variance_bounds)
    __ne__ = _swig_new_instance_method(_eec.EECHistBaseLogLogId___ne__)
    __eq__ = _swig_new_instance_method(_eec.EECHistBaseLogLogId___eq__)
    hists_as_text = _swig_new_instance_method(_eec.EECHistBaseLogLogId_hists_as_text)
    bin_centers = _swig_new_instance_method(_eec.EECHistBaseLogLogId_bin_centers)
    bin_edges = _swig_new_instance_method(_eec.EECHistBaseLogLogId_bin_edges)
    scale = _swig_new_instance_method(_eec.EECHistBaseLogLogId_scale)

    def get_hist_errs(self, hist_i=0, overflows=True):
        hist, vars = self.get_hist_vars(hist_i, overflows)
        return hist, _np.sqrt(vars)

    def get_error_bound(self, hist_i=0, overflows=True):
        return _np.sqrt(self.get_variance_bound(hist_i, overflows))


# Register EECHistBaseLogLogId in _eec:
_eec.EECHistBaseLogLogId_swigregister(EECHistBaseLogLogId)
EECHistBaseLogLogId_rank = _eec.EECHistBaseLogLogId_rank

class EECHist1DId(EECHistBase1DId):
    r"""Proxy of C++ fastjet::contrib::eec::hist::EECHist1D< axis::id > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _eec.delete_EECHist1DId
    hist_name = _swig_new_static_method(_eec.EECHist1DId_hist_name)
    axes_description = _swig_new_static_method(_eec.EECHist1DId_axes_description)
    get_hist_vars = _swig_new_instance_method(_eec.EECHist1DId_get_hist_vars)
    get_covariance = _swig_new_instance_method(_eec.EECHist1DId_get_covariance)
    get_variance_bound = _swig_new_instance_method(_eec.EECHist1DId_get_variance_bound)

# Register EECHist1DId in _eec:
_eec.EECHist1DId_swigregister(EECHist1DId)
EECHist1DId_hist_name = _eec.EECHist1DId_hist_name
EECHist1DId_axes_description = _eec.EECHist1DId_axes_description

class EECHist1DLog(EECHistBase1DLog):
    r"""Proxy of C++ fastjet::contrib::eec::hist::EECHist1D< axis::log > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _eec.delete_EECHist1DLog
    hist_name = _swig_new_static_method(_eec.EECHist1DLog_hist_name)
    axes_description = _swig_new_static_method(_eec.EECHist1DLog_axes_description)
    get_hist_vars = _swig_new_instance_method(_eec.EECHist1DLog_get_hist_vars)
    get_covariance = _swig_new_instance_method(_eec.EECHist1DLog_get_covariance)
    get_variance_bound = _swig_new_instance_method(_eec.EECHist1DLog_get_variance_bound)

# Register EECHist1DLog in _eec:
_eec.EECHist1DLog_swigregister(EECHist1DLog)
EECHist1DLog_hist_name = _eec.EECHist1DLog_hist_name
EECHist1DLog_axes_description = _eec.EECHist1DLog_axes_description

class EECHist3DIdIdId(EECHistBaseIdIdId):
    r"""Proxy of C++ fastjet::contrib::eec::hist::EECHist3D< axis::id,axis::id,axis::id > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _eec.delete_EECHist3DIdIdId
    hist_name = _swig_new_static_method(_eec.EECHist3DIdIdId_hist_name)
    axes_description = _swig_new_static_method(_eec.EECHist3DIdIdId_axes_description)
    get_hist_vars = _swig_new_instance_method(_eec.EECHist3DIdIdId_get_hist_vars)
    get_covariance = _swig_new_instance_method(_eec.EECHist3DIdIdId_get_covariance)
    get_variance_bound = _swig_new_instance_method(_eec.EECHist3DIdIdId_get_variance_bound)

# Register EECHist3DIdIdId in _eec:
_eec.EECHist3DIdIdId_swigregister(EECHist3DIdIdId)
EECHist3DIdIdId_hist_name = _eec.EECHist3DIdIdId_hist_name
EECHist3DIdIdId_axes_description = _eec.EECHist3DIdIdId_axes_description

class EECHist3DLogIdId(EECHistBaseLogIdId):
    r"""Proxy of C++ fastjet::contrib::eec::hist::EECHist3D< axis::log,axis::id,axis::id > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _eec.delete_EECHist3DLogIdId
    hist_name = _swig_new_static_method(_eec.EECHist3DLogIdId_hist_name)
    axes_description = _swig_new_static_method(_eec.EECHist3DLogIdId_axes_description)
    get_hist_vars = _swig_new_instance_method(_eec.EECHist3DLogIdId_get_hist_vars)
    get_covariance = _swig_new_instance_method(_eec.EECHist3DLogIdId_get_covariance)
    get_variance_bound = _swig_new_instance_method(_eec.EECHist3DLogIdId_get_variance_bound)

# Register EECHist3DLogIdId in _eec:
_eec.EECHist3DLogIdId_swigregister(EECHist3DLogIdId)
EECHist3DLogIdId_hist_name = _eec.EECHist3DLogIdId_hist_name
EECHist3DLogIdId_axes_description = _eec.EECHist3DLogIdId_axes_description

class EECHist3DIdLogId(EECHistBaseIdLogId):
    r"""Proxy of C++ fastjet::contrib::eec::hist::EECHist3D< axis::id,axis::log,axis::id > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _eec.delete_EECHist3DIdLogId
    hist_name = _swig_new_static_method(_eec.EECHist3DIdLogId_hist_name)
    axes_description = _swig_new_static_method(_eec.EECHist3DIdLogId_axes_description)
    get_hist_vars = _swig_new_instance_method(_eec.EECHist3DIdLogId_get_hist_vars)
    get_covariance = _swig_new_instance_method(_eec.EECHist3DIdLogId_get_covariance)
    get_variance_bound = _swig_new_instance_method(_eec.EECHist3DIdLogId_get_variance_bound)

# Register EECHist3DIdLogId in _eec:
_eec.EECHist3DIdLogId_swigregister(EECHist3DIdLogId)
EECHist3DIdLogId_hist_name = _eec.EECHist3DIdLogId_hist_name
EECHist3DIdLogId_axes_description = _eec.EECHist3DIdLogId_axes_description

class EECHist3DLogLogId(EECHistBaseLogLogId):
    r"""Proxy of C++ fastjet::contrib::eec::hist::EECHist3D< axis::log,axis::log,axis::id > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _eec.delete_EECHist3DLogLogId
    hist_name = _swig_new_static_method(_eec.EECHist3DLogLogId_hist_name)
    axes_description = _swig_new_static_method(_eec.EECHist3DLogLogId_axes_description)
    get_hist_vars = _swig_new_instance_method(_eec.EECHist3DLogLogId_get_hist_vars)
    get_covariance = _swig_new_instance_method(_eec.EECHist3DLogLogId_get_covariance)
    get_variance_bound = _swig_new_instance_method(_eec.EECHist3DLogLogId_get_variance_bound)

# Register EECHist3DLogLogId in _eec:
_eec.EECHist3DLogLogId_swigregister(EECHist3DLogLogId)
EECHist3DLogLogId_hist_name = _eec.EECHist3DLogLogId_hist_name
EECHist3DLogLogId_axes_description = _eec.EECHist3DLogLogId_axes_description

class EECBase(object):
    r"""Proxy of C++ fastjet::contrib::eec::EECBase class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _eec.delete_EECBase
    _compute = _swig_new_instance_method(_eec.EECBase__compute)
    _push_back = _swig_new_instance_method(_eec.EECBase__push_back)
    clear_events = _swig_new_instance_method(_eec.EECBase_clear_events)
    batch_compute = _swig_new_instance_method(_eec.EECBase_batch_compute)
    config = _swig_new_instance_method(_eec.EECBase_config)
    compname = _swig_new_instance_method(_eec.EECBase_compname)
    N = _swig_new_instance_method(_eec.EECBase_N)
    nfeatures = _swig_new_instance_method(_eec.EECBase_nfeatures)
    nsym = _swig_new_instance_method(_eec.EECBase_nsym)
    weight_powers = _swig_new_instance_method(_eec.EECBase_weight_powers)
    charge_powers = _swig_new_instance_method(_eec.EECBase_charge_powers)
    norm = _swig_new_instance_method(_eec.EECBase_norm)
    use_charges = _swig_new_instance_method(_eec.EECBase_use_charges)
    check_degen = _swig_new_instance_method(_eec.EECBase_check_degen)
    average_verts = _swig_new_instance_method(_eec.EECBase_average_verts)
    num_threads = _swig_new_instance_method(_eec.EECBase_num_threads)
    omp_chunksize = _swig_new_instance_method(_eec.EECBase_omp_chunksize)
    print_every = _swig_new_instance_method(_eec.EECBase_print_every)
    total_weight = _swig_new_instance_method(_eec.EECBase_total_weight)
    particle_weight = _swig_new_instance_method(_eec.EECBase_particle_weight)
    pairwise_distance = _swig_new_instance_method(_eec.EECBase_pairwise_distance)
    set_weight_powers = _swig_new_instance_method(_eec.EECBase_set_weight_powers)
    set_charge_powers = _swig_new_instance_method(_eec.EECBase_set_charge_powers)
    set_norm = _swig_new_instance_method(_eec.EECBase_set_norm)
    set_check_degen = _swig_new_instance_method(_eec.EECBase_set_check_degen)
    set_average_verts = _swig_new_instance_method(_eec.EECBase_set_average_verts)
    set_num_threads = _swig_new_instance_method(_eec.EECBase_set_num_threads)
    set_omp_chunksize = _swig_new_instance_method(_eec.EECBase_set_omp_chunksize)
    set_print_every = _swig_new_instance_method(_eec.EECBase_set_print_every)
    set_particle_weight = _swig_new_instance_method(_eec.EECBase_set_particle_weight)
    set_pairwise_distance = _swig_new_instance_method(_eec.EECBase_set_pairwise_distance)
    __ne__ = _swig_new_instance_method(_eec.EECBase___ne__)
    __eq__ = _swig_new_instance_method(_eec.EECBase___eq__)

    def __repr__(self):
        return self.description().decode('utf-8')


    def __getstate__(self):
        return (self.__getstate_internal__(),)

    def __setstate__(self, state):
        self.__init__(*self._default_args)
        try:
            self.__setstate_internal__(state[0])
        except Exception as e:
            raise RuntimeError('issue loading eec - check `eec.get_archive_format()`'
                               ' and `eec.get_compression_mode()`',
                               repr(e))



    def compute(self, event, event_weight=1.0, charges=None, dists=None, thread=0):
        self._compute(*_get_eec_args(event, charges, dists, self.nfeatures()), event_weight, thread)

    def __call__(self, events, event_weights=None, charges=None, dists=None):

        if event_weights is None:
            event_weights = _np.ones(len(events), dtype=_np.double)
        elif len(event_weights) != len(events):
            raise ValueError('`events` and `event_weights` have different lengths')

        if charges is None:
            charges = len(events)*[None]
        elif len(charges) != len(events):
            raise ValueError('`events` and `charges` have different lengths')

        if dists is None:
            dists = len(events)*[None]
        elif len(dists) != len(events):
            raise ValueError('`events` and `dists` have different lengths')

        nf = self.nfeatures()
        for event, chs, ds, event_weight in zip(events, charges, dists, event_weights):
            self._push_back(*_get_eec_args(event, chs, ds, nf), event_weight)

        self.batch_compute()
        self.clear_events()


# Register EECBase in _eec:
_eec.EECBase_swigregister(EECBase)

multinomial = _eec.multinomial
class DynamicMultinomial(object):
    r"""Proxy of C++ fastjet::contrib::eec::DynamicMultinomial class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, N: "unsigned int"):
        r"""__init__(DynamicMultinomial self, unsigned int N) -> DynamicMultinomial"""
        _eec.DynamicMultinomial_swiginit(self, _eec.new_DynamicMultinomial(N))
    N = _swig_new_instance_method(_eec.DynamicMultinomial_N)
    set_index = _swig_new_instance_method(_eec.DynamicMultinomial_set_index)
    value = _swig_new_instance_method(_eec.DynamicMultinomial_value)
    __swig_destroy__ = _eec.delete_DynamicMultinomial

# Register DynamicMultinomial in _eec:
_eec.DynamicMultinomial_swigregister(DynamicMultinomial)
FACTORIALS = cvar.FACTORIALS


def _get_eec_args(event, charges, dists, nfeatures):

    if charges is None:
        charges = []

    if (len(event) == 0 or
        isinstance(event, pyfjcore.PseudoJetContainer) or
        isinstance(event[0], pyfjcore.PseudoJet)):
        return (event, charges)

    if dists is None:
        return (_np.atleast_2d(event)[:,:nfeatures],)

    return (event, dists, charges)

class Multinomial2(object):
    r"""Proxy of C++ fastjet::contrib::eec::Multinomial< 2 > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(Multinomial2 self) -> Multinomial2"""
        _eec.Multinomial2_swiginit(self, _eec.new_Multinomial2())
    N = _swig_new_static_method(_eec.Multinomial2_N)
    set_index_0 = _swig_new_instance_method(_eec.Multinomial2_set_index_0)
    set_index_final = _swig_new_instance_method(_eec.Multinomial2_set_index_final)
    value = _swig_new_instance_method(_eec.Multinomial2_value)
    set_index_1 = _swig_new_instance_method(_eec.Multinomial2_set_index_1)
    set_index_2 = _swig_new_instance_method(_eec.Multinomial2_set_index_2)
    set_index_3 = _swig_new_instance_method(_eec.Multinomial2_set_index_3)
    set_index_4 = _swig_new_instance_method(_eec.Multinomial2_set_index_4)
    __swig_destroy__ = _eec.delete_Multinomial2

# Register Multinomial2 in _eec:
_eec.Multinomial2_swigregister(Multinomial2)
Multinomial2_N = _eec.Multinomial2_N

class Multinomial3(object):
    r"""Proxy of C++ fastjet::contrib::eec::Multinomial< 3 > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(Multinomial3 self) -> Multinomial3"""
        _eec.Multinomial3_swiginit(self, _eec.new_Multinomial3())
    N = _swig_new_static_method(_eec.Multinomial3_N)
    set_index_0 = _swig_new_instance_method(_eec.Multinomial3_set_index_0)
    set_index_final = _swig_new_instance_method(_eec.Multinomial3_set_index_final)
    value = _swig_new_instance_method(_eec.Multinomial3_value)
    set_index_1 = _swig_new_instance_method(_eec.Multinomial3_set_index_1)
    set_index_2 = _swig_new_instance_method(_eec.Multinomial3_set_index_2)
    set_index_3 = _swig_new_instance_method(_eec.Multinomial3_set_index_3)
    set_index_4 = _swig_new_instance_method(_eec.Multinomial3_set_index_4)
    __swig_destroy__ = _eec.delete_Multinomial3

# Register Multinomial3 in _eec:
_eec.Multinomial3_swigregister(Multinomial3)
Multinomial3_N = _eec.Multinomial3_N

class Multinomial4(object):
    r"""Proxy of C++ fastjet::contrib::eec::Multinomial< 4 > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(Multinomial4 self) -> Multinomial4"""
        _eec.Multinomial4_swiginit(self, _eec.new_Multinomial4())
    N = _swig_new_static_method(_eec.Multinomial4_N)
    set_index_0 = _swig_new_instance_method(_eec.Multinomial4_set_index_0)
    set_index_final = _swig_new_instance_method(_eec.Multinomial4_set_index_final)
    value = _swig_new_instance_method(_eec.Multinomial4_value)
    set_index_1 = _swig_new_instance_method(_eec.Multinomial4_set_index_1)
    set_index_2 = _swig_new_instance_method(_eec.Multinomial4_set_index_2)
    set_index_3 = _swig_new_instance_method(_eec.Multinomial4_set_index_3)
    set_index_4 = _swig_new_instance_method(_eec.Multinomial4_set_index_4)
    __swig_destroy__ = _eec.delete_Multinomial4

# Register Multinomial4 in _eec:
_eec.Multinomial4_swigregister(Multinomial4)
Multinomial4_N = _eec.Multinomial4_N

class Multinomial5(object):
    r"""Proxy of C++ fastjet::contrib::eec::Multinomial< 5 > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(Multinomial5 self) -> Multinomial5"""
        _eec.Multinomial5_swiginit(self, _eec.new_Multinomial5())
    N = _swig_new_static_method(_eec.Multinomial5_N)
    set_index_0 = _swig_new_instance_method(_eec.Multinomial5_set_index_0)
    set_index_final = _swig_new_instance_method(_eec.Multinomial5_set_index_final)
    value = _swig_new_instance_method(_eec.Multinomial5_value)
    set_index_1 = _swig_new_instance_method(_eec.Multinomial5_set_index_1)
    set_index_2 = _swig_new_instance_method(_eec.Multinomial5_set_index_2)
    set_index_3 = _swig_new_instance_method(_eec.Multinomial5_set_index_3)
    set_index_4 = _swig_new_instance_method(_eec.Multinomial5_set_index_4)
    __swig_destroy__ = _eec.delete_Multinomial5

# Register Multinomial5 in _eec:
_eec.Multinomial5_swigregister(Multinomial5)
Multinomial5_N = _eec.Multinomial5_N

class Multinomial6(object):
    r"""Proxy of C++ fastjet::contrib::eec::Multinomial< 6 > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(Multinomial6 self) -> Multinomial6"""
        _eec.Multinomial6_swiginit(self, _eec.new_Multinomial6())
    N = _swig_new_static_method(_eec.Multinomial6_N)
    set_index_0 = _swig_new_instance_method(_eec.Multinomial6_set_index_0)
    set_index_final = _swig_new_instance_method(_eec.Multinomial6_set_index_final)
    value = _swig_new_instance_method(_eec.Multinomial6_value)
    set_index_1 = _swig_new_instance_method(_eec.Multinomial6_set_index_1)
    set_index_2 = _swig_new_instance_method(_eec.Multinomial6_set_index_2)
    set_index_3 = _swig_new_instance_method(_eec.Multinomial6_set_index_3)
    set_index_4 = _swig_new_instance_method(_eec.Multinomial6_set_index_4)
    __swig_destroy__ = _eec.delete_Multinomial6

# Register Multinomial6 in _eec:
_eec.Multinomial6_swigregister(Multinomial6)
Multinomial6_N = _eec.Multinomial6_N

class EECLongestSideId(EECBase, EECHist1DId):
    r"""Proxy of C++ fastjet::contrib::eec::EECLongestSide< axis::id > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args, **kwargs):
        r"""__init__(EECLongestSideId self, unsigned int N, unsigned int nbins, arrayDouble2 axis_range={1e-5, 1}, bool norm=True, vectorDouble weight_powers={1}, vectorUnsigned charge_powers={0}, fastjet::contrib::eec::ParticleWeight particle_weight=TransverseMomentum, fastjet::contrib::eec::PairwiseDistance pairwise_distance=DeltaR, int num_threads=-1, int omp_chunksize=10, long print_every=-10, bool check_degen=False, bool average_verts=False, bool track_covariance=True, bool variance_bound=True, bool variance_bound_includes_overflows=True, bool use_general_eNc=False) -> EECLongestSideId"""
        _eec.EECLongestSideId_swiginit(self, _eec.new_EECLongestSideId(*args, **kwargs))
    __swig_destroy__ = _eec.delete_EECLongestSideId
    use_general_eNc = _swig_new_instance_method(_eec.EECLongestSideId_use_general_eNc)
    set_use_general_eNc = _swig_new_instance_method(_eec.EECLongestSideId_set_use_general_eNc)
    set_num_threads = _swig_new_instance_method(_eec.EECLongestSideId_set_num_threads)
    description = _swig_new_instance_method(_eec.EECLongestSideId_description)
    __ne__ = _swig_new_instance_method(_eec.EECLongestSideId___ne__)
    __eq__ = _swig_new_instance_method(_eec.EECLongestSideId___eq__)
    add = _swig_new_instance_method(_eec.EECLongestSideId_add)

    def __repr__(self):
        return self.description().decode('utf-8')

    __getstate_internal__ = _swig_new_instance_method(_eec.EECLongestSideId___getstate_internal__)
    __setstate_internal__ = _swig_new_instance_method(_eec.EECLongestSideId___setstate_internal__)

    _default_args = (2, 1)


# Register EECLongestSideId in _eec:
_eec.EECLongestSideId_swigregister(EECLongestSideId)

class EECLongestSideLog(EECBase, EECHist1DLog):
    r"""Proxy of C++ fastjet::contrib::eec::EECLongestSide< axis::log > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args, **kwargs):
        r"""__init__(EECLongestSideLog self, unsigned int N, unsigned int nbins, arrayDouble2 axis_range={1e-5, 1}, bool norm=True, vectorDouble weight_powers={1}, vectorUnsigned charge_powers={0}, fastjet::contrib::eec::ParticleWeight particle_weight=TransverseMomentum, fastjet::contrib::eec::PairwiseDistance pairwise_distance=DeltaR, int num_threads=-1, int omp_chunksize=10, long print_every=-10, bool check_degen=False, bool average_verts=False, bool track_covariance=True, bool variance_bound=True, bool variance_bound_includes_overflows=True, bool use_general_eNc=False) -> EECLongestSideLog"""
        _eec.EECLongestSideLog_swiginit(self, _eec.new_EECLongestSideLog(*args, **kwargs))
    __swig_destroy__ = _eec.delete_EECLongestSideLog
    use_general_eNc = _swig_new_instance_method(_eec.EECLongestSideLog_use_general_eNc)
    set_use_general_eNc = _swig_new_instance_method(_eec.EECLongestSideLog_set_use_general_eNc)
    set_num_threads = _swig_new_instance_method(_eec.EECLongestSideLog_set_num_threads)
    description = _swig_new_instance_method(_eec.EECLongestSideLog_description)
    __ne__ = _swig_new_instance_method(_eec.EECLongestSideLog___ne__)
    __eq__ = _swig_new_instance_method(_eec.EECLongestSideLog___eq__)
    add = _swig_new_instance_method(_eec.EECLongestSideLog_add)

    def __repr__(self):
        return self.description().decode('utf-8')

    __getstate_internal__ = _swig_new_instance_method(_eec.EECLongestSideLog___getstate_internal__)
    __setstate_internal__ = _swig_new_instance_method(_eec.EECLongestSideLog___setstate_internal__)

    _default_args = (2, 1)


# Register EECLongestSideLog in _eec:
_eec.EECLongestSideLog_swigregister(EECLongestSideLog)

class EECTriangleOPEIdIdId(EECBase, EECHist3DIdIdId):
    r"""Proxy of C++ fastjet::contrib::eec::EECTriangleOPE< axis::id,axis::id,axis::id > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args, **kwargs):
        r"""__init__(EECTriangleOPEIdIdId self, arrayUnsigned3 nbins, arrayPairDoubleDouble axes_range={{{1e-5, 1}, {1e-5, 1}, {0, PI/2}}}, bool norm=True, vectorDouble weight_powers={1}, vectorUnsigned charge_powers={0}, fastjet::contrib::eec::ParticleWeight particle_weight=TransverseMomentum, fastjet::contrib::eec::PairwiseDistance pairwise_distance=DeltaR, int num_threads=-1, int omp_chunksize=10, long print_every=-10, bool check_degen=False, bool average_verts=False, bool track_covariance=False, bool variance_bound=True, bool variance_bound_includes_overflows=True) -> EECTriangleOPEIdIdId"""
        _eec.EECTriangleOPEIdIdId_swiginit(self, _eec.new_EECTriangleOPEIdIdId(*args, **kwargs))
    __swig_destroy__ = _eec.delete_EECTriangleOPEIdIdId
    set_num_threads = _swig_new_instance_method(_eec.EECTriangleOPEIdIdId_set_num_threads)
    description = _swig_new_instance_method(_eec.EECTriangleOPEIdIdId_description)
    __ne__ = _swig_new_instance_method(_eec.EECTriangleOPEIdIdId___ne__)
    __eq__ = _swig_new_instance_method(_eec.EECTriangleOPEIdIdId___eq__)
    add = _swig_new_instance_method(_eec.EECTriangleOPEIdIdId_add)

    def __repr__(self):
        return self.description().decode('utf-8')

    __getstate_internal__ = _swig_new_instance_method(_eec.EECTriangleOPEIdIdId___getstate_internal__)
    __setstate_internal__ = _swig_new_instance_method(_eec.EECTriangleOPEIdIdId___setstate_internal__)

    _default_args = ((1, 1, 1),)


# Register EECTriangleOPEIdIdId in _eec:
_eec.EECTriangleOPEIdIdId_swigregister(EECTriangleOPEIdIdId)

class EECTriangleOPELogIdId(EECBase, EECHist3DLogIdId):
    r"""Proxy of C++ fastjet::contrib::eec::EECTriangleOPE< axis::log,axis::id,axis::id > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args, **kwargs):
        r"""__init__(EECTriangleOPELogIdId self, arrayUnsigned3 nbins, arrayPairDoubleDouble axes_range={{{1e-5, 1}, {1e-5, 1}, {0, PI/2}}}, bool norm=True, vectorDouble weight_powers={1}, vectorUnsigned charge_powers={0}, fastjet::contrib::eec::ParticleWeight particle_weight=TransverseMomentum, fastjet::contrib::eec::PairwiseDistance pairwise_distance=DeltaR, int num_threads=-1, int omp_chunksize=10, long print_every=-10, bool check_degen=False, bool average_verts=False, bool track_covariance=False, bool variance_bound=True, bool variance_bound_includes_overflows=True) -> EECTriangleOPELogIdId"""
        _eec.EECTriangleOPELogIdId_swiginit(self, _eec.new_EECTriangleOPELogIdId(*args, **kwargs))
    __swig_destroy__ = _eec.delete_EECTriangleOPELogIdId
    set_num_threads = _swig_new_instance_method(_eec.EECTriangleOPELogIdId_set_num_threads)
    description = _swig_new_instance_method(_eec.EECTriangleOPELogIdId_description)
    __ne__ = _swig_new_instance_method(_eec.EECTriangleOPELogIdId___ne__)
    __eq__ = _swig_new_instance_method(_eec.EECTriangleOPELogIdId___eq__)
    add = _swig_new_instance_method(_eec.EECTriangleOPELogIdId_add)

    def __repr__(self):
        return self.description().decode('utf-8')

    __getstate_internal__ = _swig_new_instance_method(_eec.EECTriangleOPELogIdId___getstate_internal__)
    __setstate_internal__ = _swig_new_instance_method(_eec.EECTriangleOPELogIdId___setstate_internal__)

    _default_args = ((1, 1, 1),)


# Register EECTriangleOPELogIdId in _eec:
_eec.EECTriangleOPELogIdId_swigregister(EECTriangleOPELogIdId)

class EECTriangleOPEIdLogId(EECBase, EECHist3DIdLogId):
    r"""Proxy of C++ fastjet::contrib::eec::EECTriangleOPE< axis::id,axis::log,axis::id > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args, **kwargs):
        r"""__init__(EECTriangleOPEIdLogId self, arrayUnsigned3 nbins, arrayPairDoubleDouble axes_range={{{1e-5, 1}, {1e-5, 1}, {0, PI/2}}}, bool norm=True, vectorDouble weight_powers={1}, vectorUnsigned charge_powers={0}, fastjet::contrib::eec::ParticleWeight particle_weight=TransverseMomentum, fastjet::contrib::eec::PairwiseDistance pairwise_distance=DeltaR, int num_threads=-1, int omp_chunksize=10, long print_every=-10, bool check_degen=False, bool average_verts=False, bool track_covariance=False, bool variance_bound=True, bool variance_bound_includes_overflows=True) -> EECTriangleOPEIdLogId"""
        _eec.EECTriangleOPEIdLogId_swiginit(self, _eec.new_EECTriangleOPEIdLogId(*args, **kwargs))
    __swig_destroy__ = _eec.delete_EECTriangleOPEIdLogId
    set_num_threads = _swig_new_instance_method(_eec.EECTriangleOPEIdLogId_set_num_threads)
    description = _swig_new_instance_method(_eec.EECTriangleOPEIdLogId_description)
    __ne__ = _swig_new_instance_method(_eec.EECTriangleOPEIdLogId___ne__)
    __eq__ = _swig_new_instance_method(_eec.EECTriangleOPEIdLogId___eq__)
    add = _swig_new_instance_method(_eec.EECTriangleOPEIdLogId_add)

    def __repr__(self):
        return self.description().decode('utf-8')

    __getstate_internal__ = _swig_new_instance_method(_eec.EECTriangleOPEIdLogId___getstate_internal__)
    __setstate_internal__ = _swig_new_instance_method(_eec.EECTriangleOPEIdLogId___setstate_internal__)

    _default_args = ((1, 1, 1),)


# Register EECTriangleOPEIdLogId in _eec:
_eec.EECTriangleOPEIdLogId_swigregister(EECTriangleOPEIdLogId)

class EECTriangleOPELogLogId(EECBase, EECHist3DLogLogId):
    r"""Proxy of C++ fastjet::contrib::eec::EECTriangleOPE< axis::log,axis::log,axis::id > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args, **kwargs):
        r"""__init__(EECTriangleOPELogLogId self, arrayUnsigned3 nbins, arrayPairDoubleDouble axes_range={{{1e-5, 1}, {1e-5, 1}, {0, PI/2}}}, bool norm=True, vectorDouble weight_powers={1}, vectorUnsigned charge_powers={0}, fastjet::contrib::eec::ParticleWeight particle_weight=TransverseMomentum, fastjet::contrib::eec::PairwiseDistance pairwise_distance=DeltaR, int num_threads=-1, int omp_chunksize=10, long print_every=-10, bool check_degen=False, bool average_verts=False, bool track_covariance=False, bool variance_bound=True, bool variance_bound_includes_overflows=True) -> EECTriangleOPELogLogId"""
        _eec.EECTriangleOPELogLogId_swiginit(self, _eec.new_EECTriangleOPELogLogId(*args, **kwargs))
    __swig_destroy__ = _eec.delete_EECTriangleOPELogLogId
    set_num_threads = _swig_new_instance_method(_eec.EECTriangleOPELogLogId_set_num_threads)
    description = _swig_new_instance_method(_eec.EECTriangleOPELogLogId_description)
    __ne__ = _swig_new_instance_method(_eec.EECTriangleOPELogLogId___ne__)
    __eq__ = _swig_new_instance_method(_eec.EECTriangleOPELogLogId___eq__)
    add = _swig_new_instance_method(_eec.EECTriangleOPELogLogId_add)

    def __repr__(self):
        return self.description().decode('utf-8')

    __getstate_internal__ = _swig_new_instance_method(_eec.EECTriangleOPELogLogId___getstate_internal__)
    __setstate_internal__ = _swig_new_instance_method(_eec.EECTriangleOPELogLogId___setstate_internal__)

    _default_args = ((1, 1, 1),)


# Register EECTriangleOPELogLogId in _eec:
_eec.EECTriangleOPELogLogId_swigregister(EECTriangleOPELogLogId)



